In [ ]:
# Name: Nimotallahi Abiodun Durojaiye
# WTF ID: WTF/2025/5891
# MAIL: nimotallahi02@outlook.com

In [ ]:
# 1. np.array()
# np.array()
# Creates an array from a list or tuple.
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [ ]:
#2. np.arange()
# Creates an array with evenly spaced values within a given interval.
b = np.arange(0, 10, 2)



In [ ]:
# 3. np.linspace()
# Creates an array with a specified number of evenly spaced values.
c = np.linspace(0, 1, 5)
c

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# 4. np.zeros()
# Creates an array filled with zeros.
d = np.zeros((2, 3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 5. np.ones()
# Creates an array filled with ones.
e = np.ones((3, 2))
e

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# 6. np.eye()
# Creates a 2D identity matrix.
f = np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 7. np.full()
# Creates an array filled with a specified value.
g = np.full((2, 3), 7)
g

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
# 8. np.reshape()
# Changes the shape of an array without changing its data.
h = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
h

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 9. np.mean()
# Computes the arithmetic mean along the specified axis.
i = np.array([1, 2, 3, 4, 5])
mean_val = np.mean(i)
mean_val

np.float64(3.0)

In [ ]:
# 10. np.median()
# Computes the median along the specified axis.
j = np.array([1, 2, 3, 4, 5, 6, 7])
median_val = np.median(j)
median_val

np.float64(4.0)

In [ ]:
# 11. np.sum()
# Calculates the sum of array elements.
k = np.array([[1, 2], [3, 4]])
total = np.sum(k)
total

np.int64(10)

In [ ]:
#12. np.max()
# Returns the maximum value from an array.
l = np.array([5, 2, 8, 1, 9])
max_val = np.max(l)
max_val

np.int64(9)

In [ ]:
#13. np.min()
# Returns the minimum value from an array.
m = np.array([5, 2, 8, 1, 9])
min_val = np.min(m)
min_val

np.int64(1)

In [ ]:
# 14. np.std()
# Computes the standard deviation.
n = np.array([1, 2, 3, 4, 5])
std_dev = np.std(n)
std_dev

np.float64(1.4142135623730951)

In [ ]:
#15. np.var()
# Computes the variance.
o = np.array([1, 2, 3, 4, 5])
variance = np.var(o)
variance

np.float64(2.0)

In [ ]:
#16. np.dot()
# Computes the dot product of two arrays.
p = np.array([1, 2, 3])
q = np.array([4, 5, 6])
ans = np.dot(p, q)
ans

np.int64(32)

In [ ]:
#17. np.transpose()
# Reverses or permutes the axes of an array.
r = np.array([[1, 2, 3], [4, 5, 6]])
transposed = np.transpose(r)
transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#18. np.concatenate()
# Joins two or more arrays along an existing axis.
s = np.array([1, 2, 3])
t = np.array([4, 5, 6])
ans = np.concatenate([s, t])
ans

array([1, 2, 3, 4, 5, 6])

In [ ]:
#19. np.vstack()
# Stacks arrays vertically (row-wise).
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
ans = np.vstack([u, v])
ans

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#20. np.hstack()
# Stacks arrays horizontally (column-wise).
w = np.array([1, 2, 3])
x = np.array([4, 5, 6])
ans = np.hstack([w, x])
ans

array([1, 2, 3, 4, 5, 6])

In [ ]:
#21.np.split()
# Splits an array into multiple sub-arrays.
y = np.array([1, 2, 3, 4, 5, 6])
ans = np.split(y, 3)
ans

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
#22. np.where()
# Returns elements chosen from x or y depending on condition.
z = np.array([1, 2, 3, 4, 5])
ans = np.where(z > 3, 'high', 'low')
ans

array(['low', 'low', 'low', 'high', 'high'], dtype='<U4')

In [ ]:
#23. np.sort()
# Returns a sorted copy of an array.
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])
sorted_arr = np.sort(a)
sorted_arr

array([1, 1, 2, 3, 4, 5, 6, 9])

In [ ]:
#24. np.argsort()
# Returns the indices that would sort an array.
b = np.array([3, 1, 2])
indices = np.argsort(b)
indices

array([1, 2, 0])

In [ ]:
#25. np.unique()
# Finds the unique elements of an array.
c = np.array([1, 2, 2, 3, 3, 3, 4])
unique_vals = np.unique(c)
unique_vals

array([1, 2, 3, 4])

In [ ]:
#26. np.argmax()
# Returns the indices of the maximum values.
d = np.array([10, 5, 8, 15, 3])
index = np.argmax(d)
index

np.int64(3)

In [ ]:
#27. np.argmin()
# Returns the indices of the minimum values.
e = np.array([10, 5, 8, 15, 3])
index = np.argmin(e)
index

np.int64(4)

In [ ]:
#28. np.abs()
# Computes the absolute value element-wise.
f = np.array([-1, -2, 3, -4])
ans = np.abs(f)
ans

array([1, 2, 3, 4])

In [ ]:
# 29. np.sqrt()
# Computes the square root element-wise.
g = np.array([1, 4, 9, 16])
ans = np.sqrt(g)
ans

array([1., 2., 3., 4.])

In [ ]:
#30. np.power()
# Raises elements to specified powers.
h = np.array([1, 2, 3, 4])
ans = np.power(h, 2)
ans

array([ 1,  4,  9, 16])

In [ ]:
#31. np.exp()
# Computes the exponential of all elements.
i = np.array([1, 2, 3])
ans = np.exp(i)
ans

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
#32.np.log()
# Computes natural logarithm element-wise.
j = np.array([1, 2, 3])
ans = np.log(j)
ans

array([0.        , 0.69314718, 1.09861229])

In [ ]:
#33. np.floor()
# Returns the floor of the input element-wise.
k = np.array([1.7, 2.3, 3.9])
ans = np.floor(k)
ans

array([1., 2., 3.])

In [ ]:
#34. np.ceil()
# Returns the ceiling of the input element-wise.
l = np.array([1.2, 2.5, 3.1])
ans = np.ceil(l)
ans

array([2., 3., 4.])

In [ ]:
#35. np.round()
# Rounds elements to the nearest integer.
k = np.array([1.4, 2.6, 3.5])
ans = np.round(k)
ans

array([1., 3., 4.])

In [ ]:
#36. np.clip()
# Clips values to a specified range.
l = np.array([1, 5, 10, 15])
ans = np.clip(l, 3, 12)
ans

array([ 3,  5, 10, 12])

In [ ]:
#37. np.random.rand()
# Creates an array of random values in [0, 1).
m = np.random.rand(2, 3)
m

array([[0.1241182 , 0.60310345, 0.16315958],
       [0.84635695, 0.72154793, 0.51140009]])

In [ ]:
#38. np.random.randint()
# Generates random integers from low to high.
n = np.random.randint(1, 10, size=5)
n

array([3, 3, 7, 1, 9])

In [ ]:
#39. np.random.randn()
# Generates samples from standard normal distribution.
o = np.random.randn(3, 2)
o

array([[ 0.62660788,  0.38656352],
       [-2.11878829,  0.620193  ],
       [ 0.27857315, -1.05854912]])

In [ ]:
#40. np.random.choice()
# Generates a random sample from a given array.
p = np.array([1, 2, 3, 4, 5])
ans = np.random.choice(p, size=3, replace=False)
ans

array([1, 4, 2])

In [ ]:
# PANDA METHOD

In [ ]:
#1. pd.DataFrame()
# Creates a DataFrame from various data structures.
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df

,A,B
0,1,4
1,2,5
2,3,6


In [ ]:
#2. pd.Series()
# Creates a one-dimensional labeled array.
s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s

,0
a,1
b,2
c,3
d,4


In [ ]:
#3. pd.read_csv()
# Reads a CSV file into a DataFrame.

import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("table-16d34121-c818-485c-bdc8-3eae4b54bf91-2.csv")
df.head()



KeyboardInterrupt: 

In [ ]:
# 4. pd.read_excel()
# Reads an Excel file into a DataFrame.

from google.colab import drive
drive.mount('/content/drive')

df_sales = pd.read_excel(
    "/content/drive/MyDrive/Copy of Palmpay Test 2 (1).xlsx",
    sheet_name="Sales"
)
df_sales


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


,YEAR,MONTH,DAY,Customer,CustomerDescr,City,Salesorg,Country,OrderNumber,OrderItem,...,Division,SalesQuantity,UnitOfMeasure,Revenue,Currency,Discount,CostOfGoodsManufactured,Revenue USD,Discount USD,Cogm USD
0,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,10,...,BI,2,ST,6000.00,USD,300.0,2800.00,6000.00,300.0,2800.0
1,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,20,...,BI,5,ST,16000.00,USD,800.0,7500.00,16000.00,800.0,7500.0
2,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,30,...,BI,1,ST,2400.00,USD,120.0,1200.00,2400.00,120.0,1200.0
3,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,40,...,BI,1,ST,1600.00,USD,80.0,900.00,1600.00,80.0,900.0
4,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,50,...,BI,7,ST,11900.00,USD,595.0,7000.00,11900.00,595.0,7000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48379,2011,12,31,19000,Fahrpott,Bochum,DN00,DE,103318,80,...,AS,1,ST,43.35,EUR,0.0,33.66,58.37,0.0,25.0
48380,2011,12,31,19000,Fahrpott,Bochum,DN00,DE,103318,90,...,AS,2,ST,31.22,EUR,0.0,24.24,42.04,0.0,18.0
48381,2011,12,31,19000,Fahrpott,Bochum,DN00,DE,103318,100,...,AS,1,ST,27.75,EUR,0.0,21.54,37.37,0.0,16.0
48382,2011,12,31,19000,Fahrpott,Bochum,DN00,DE,103318,110,...,AS,2,ST,48.56,EUR,0.0,37.70,65.39,0.0,28.0


In [ ]:
#5. df.head()
# Returns the first n rows of a DataFrame.
from google.colab import drive
drive.mount('/content/drive')

df_sales = pd.read_excel(
    "/content/drive/MyDrive/Copy of Palmpay Test 2 (1).xlsx",
    sheet_name="Sales"
)
df_sales.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


,YEAR,MONTH,DAY,Customer,CustomerDescr,City,Salesorg,Country,OrderNumber,OrderItem,...,Division,SalesQuantity,UnitOfMeasure,Revenue,Currency,Discount,CostOfGoodsManufactured,Revenue USD,Discount USD,Cogm USD
0,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,10,...,BI,2,ST,6000.0,USD,300.0,2800.0,6000.0,300.0,2800.0
1,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,20,...,BI,5,ST,16000.0,USD,800.0,7500.0,16000.0,800.0,7500.0
2,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,30,...,BI,1,ST,2400.0,USD,120.0,1200.0,2400.0,120.0,1200.0
3,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,40,...,BI,1,ST,1600.0,USD,80.0,900.0,1600.0,80.0,900.0
4,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,50,...,BI,7,ST,11900.0,USD,595.0,7000.0,11900.0,595.0,7000.0


In [ ]:
#6. df.tail()
# Returns the last n rows of a DataFrame.

df_sales.tail()


,YEAR,MONTH,DAY,Customer,CustomerDescr,City,Salesorg,Country,OrderNumber,OrderItem,...,Division,SalesQuantity,UnitOfMeasure,Revenue,Currency,Discount,CostOfGoodsManufactured,Revenue USD,Discount USD,Cogm USD
48379,2011,12,31,19000,Fahrpott,Bochum,DN00,DE,103318,80,...,AS,1,ST,43.35,EUR,0.0,33.66,58.37,0.0,25.0
48380,2011,12,31,19000,Fahrpott,Bochum,DN00,DE,103318,90,...,AS,2,ST,31.22,EUR,0.0,24.24,42.04,0.0,18.0
48381,2011,12,31,19000,Fahrpott,Bochum,DN00,DE,103318,100,...,AS,1,ST,27.75,EUR,0.0,21.54,37.37,0.0,16.0
48382,2011,12,31,19000,Fahrpott,Bochum,DN00,DE,103318,110,...,AS,2,ST,48.56,EUR,0.0,37.70,65.39,0.0,28.0
48383,2011,12,31,19000,Fahrpott,Bochum,DN00,DE,103318,120,...,AS,1,ST,34.68,EUR,0.0,26.93,46.70,0.0,20.0


In [ ]:
#7. df.info()
# Prints a concise summary of a DataFrame.

df_sales.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48384 entries, 0 to 48383
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   YEAR                     48384 non-null  int64  
 1   MONTH                    48384 non-null  int64  
 2   DAY                      48384 non-null  int64  
 3   Customer                 48384 non-null  int64  
 4   CustomerDescr            48384 non-null  object 
 5   City                     48384 non-null  object 
 6   Salesorg                 48384 non-null  object 
 7   Country                  48384 non-null  object 
 8   OrderNumber              48384 non-null  int64  
 9   OrderItem                48384 non-null  int64  
 10  Product                  48384 non-null  object 
 11  ProductDescr             48384 non-null  object 
 12  Product Category         48384 non-null  object 
 13  Division                 48384 non-null  object 
 14  SalesQuantity         

In [ ]:
#8. df.describe()
# Generates descriptive statistics.
df_sales.describe()

,YEAR,MONTH,DAY,Customer,OrderNumber,OrderItem,SalesQuantity,Revenue,Discount,CostOfGoodsManufactured,Revenue USD,Discount USD,Cogm USD
count,48384.000000,48384.000000,48384.000000,48384.000000,48384.000000,48384.000000,48384.000000,48384.000000,48384.000000,48384.000000,48384.000000,48384.000000,48384.000000
mean,2008.931527,6.297578,11.881014,12675.181878,101646.679460,99.612682,3.489873,5025.970862,158.836738,3346.249622,5895.561933,183.319525,2810.763724
std,1.424321,2.943633,8.602282,6883.287060,966.324623,65.929313,5.482632,9965.817456,414.977611,6867.385163,11839.759324,489.389383,5608.318767
min,2007.000000,1.000000,1.000000,1000.000000,100001.000000,10.000000,1.000000,14.700000,0.000000,9.000000,18.000000,0.000000,9.000000
25%,2008.000000,4.000000,5.000000,6000.000000,100832.000000,40.000000,1.000000,85.260000,1.210000,53.860000,100.500000,1.320000,48.000000
50%,2009.000000,6.000000,10.000000,13000.000000,101664.000000,90.000000,2.000000,2500.000000,42.290000,1400.000000,3000.000000,50.950000,1400.000000
75%,2010.000000,9.000000,18.000000,18000.000000,102460.000000,150.000000,4.000000,5313.352500,154.530000,3635.550000,6496.000000,173.390000,2850.000000
max,2011.000000,12.000000,31.000000,24000.000000,103318.000000,280.000000,146.000000,297279.000000,14863.950000,234291.000000,400286.170000,20014.310000,174000.000000


In [159]:
#9. df.shape
# Returns the dimensions of the DataFrame.
df_sales.shape

(48384, 23)

In [160]:
#10. df.columns
# Returns the column labels of the DataFrame.
df_sales.columns

Index(['YEAR', 'MONTH', 'DAY', 'Customer', 'CustomerDescr', 'City', 'Salesorg',
       'Country', 'OrderNumber', 'OrderItem', 'Product', 'ProductDescr',
       'Product Category', 'Division', 'SalesQuantity', 'UnitOfMeasure',
       'Revenue', 'Currency', 'Discount', 'CostOfGoodsManufactured',
       'Revenue USD', 'Discount USD', 'Cogm USD'],
      dtype='object')

In [161]:
#11. df.dtypes
# Returns the data types of each column.
df_sales.dtypes

,0
YEAR,int64
MONTH,int64
DAY,int64
Customer,int64
CustomerDescr,object
City,object
Salesorg,object
Country,object
OrderNumber,int64
OrderItem,int64


In [163]:
#12. df.groupby()
# Groups DataFrame by one or more columns.
grouped = df_sales.groupby('Product')
grouped.head()

,YEAR,MONTH,DAY,Customer,CustomerDescr,City,Salesorg,Country,OrderNumber,OrderItem,...,Division,SalesQuantity,UnitOfMeasure,Revenue,Currency,Discount,CostOfGoodsManufactured,Revenue USD,Discount USD,Cogm USD
0,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,10,...,BI,2,ST,6000.0,USD,300.00,2800.00,6000.00,300.00,2800.0
1,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,20,...,BI,5,ST,16000.0,USD,800.00,7500.00,16000.00,800.00,7500.0
2,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,30,...,BI,1,ST,2400.0,USD,120.00,1200.00,2400.00,120.00,1200.0
3,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,40,...,BI,1,ST,1600.0,USD,80.00,900.00,1600.00,80.00,900.0
4,2007,1,1,5000,Beantown Bikes,Boston,UE00,US,100001,50,...,BI,7,ST,11900.0,USD,595.00,7000.00,11900.00,595.00,7000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30197,2010,2,1,20000,Neckarrad,Heidelberg,DS00,DE,102102,90,...,BI,1,ST,3417.0,EUR,102.51,3366.25,4600.99,138.03,2500.0
30208,2010,2,1,23000,Red Light Bikes,Hamburg,DN00,DE,102103,80,...,BI,1,ST,3417.0,EUR,102.51,3366.25,4600.99,138.03,2500.0
30288,2010,2,4,16000,Capital Bikes,Berlin,DN00,DE,102113,90,...,BI,1,ST,3417.0,EUR,102.51,3366.25,4600.99,138.03,2500.0
30307,2010,2,4,20000,Neckarrad,Heidelberg,DS00,DE,102115,120,...,BI,1,ST,3417.0,EUR,102.51,3366.25,4600.99,138.03,2500.0


In [184]:
from google.colab import drive
drive.mount('/content/drive')

df_Food1 = pd.read_excel(
    "/content/drive/MyDrive/Food.xlsx",
    sheet_name ="Data"
)
df_Food1.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


,ID,Segment,Country,Product,Discount Band,Column1,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,1,Government,Canada,Carretera,NaN,1,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,2,Government,Germany,Carretera,NaN,2,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,3,Midmarket,France,Carretera,NaN,3,2178.0,3,15,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,4,Midmarket,Germany,Carretera,NaN,4,888.0,3,15,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,5,Midmarket,Mexico,Carretera,NaN,5,2470.0,3,15,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014


In [187]:
from google.colab import drive
drive.mount('/content/drive')

df_Food2 = pd.read_excel(
    "/content/drive/MyDrive/Food.xlsx",
    sheet_name ="Facts"
)
df_Food2.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


,ID,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit
0,1,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0
1,2,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0
2,3,2178.0,3,15,32670.0,0.0,32670.0,21780.0,10890.0
3,4,888.0,3,15,13320.0,0.0,13320.0,8880.0,4440.0
4,5,2470.0,3,15,37050.0,0.0,37050.0,24700.0,12350.0


In [219]:
#13. df.merge()
# Merges two DataFrames based on common columns.
import pandas as pd
from google.colab import drive

# Ensure drive is mounted. This typically runs once per session.
drive.mount('/content/drive')

# Re-load df_Food2 to ensure it has the correct 'ID' column
# This addresses the KeyError by providing a properly structured DataFrame.
df_Food2 = pd.read_excel(
    "/content/drive/MyDrive/Food.xlsx",
    sheet_name ="Facts"
)

df_merged = df_Food1.merge(
    df_Food2,
    on='ID',
    how='left'
  )
df_merged.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


,ID,Segment,Country,Product,Discount Band,Column1,Units Sold_x,Manufacturing Price_x,Sale Price_x,Gross Sales_x,...,Month Name,Year,Units Sold_y,Manufacturing Price_y,Sale Price_y,Gross Sales_y,Discounts_y,Sales,COGS_y,Profit_y
0,1,Government,Canada,Carretera,NaN,1,1618.5,3,20,32370.0,...,January,2014,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0
1,2,Government,Germany,Carretera,NaN,2,1321.0,3,20,26420.0,...,January,2014,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0
2,3,Midmarket,France,Carretera,NaN,3,2178.0,3,15,32670.0,...,June,2014,2178.0,3,15,32670.0,0.0,32670.0,21780.0,10890.0
3,4,Midmarket,Germany,Carretera,NaN,4,888.0,3,15,13320.0,...,June,2014,888.0,3,15,13320.0,0.0,13320.0,8880.0,4440.0
4,5,Midmarket,Mexico,Carretera,NaN,5,2470.0,3,15,37050.0,...,June,2014,2470.0,3,15,37050.0,0.0,37050.0,24700.0,12350.0


In [200]:
#14. df.join()
# Joins columns of another DataFrame.
df1 = pd.DataFrame({'ID': [1, 2], 'Name': ['Alice', 'Bob']})
df2 = pd.DataFrame({'ID': [1, 2], 'Age': [25, 30]})
merged = df1.merge(df2, on='ID')
merged


,ID,Name,Age
0,1,Alice,25
1,2,Bob,30


In [169]:
#15. pd.concat()
# Concatenates pandas objects along a particular axis.
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'A': [3, 4]})
ans = pd.concat([df1, df2], ignore_index=True)
ans

,A
0,1
1,2
2,3
3,4


In [220]:
#16. df.append()
# Appends rows to the end of DataFrame (deprecated, use concat).
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'A': [3, 4]})
ans = pd.concat([df1, df2], ignore_index=True)
ans

,A
0,1
1,2
2,3
3,4


In [203]:
#17. df.dropna()
# Removes missing values from DataFrame.
df = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None]})
cleaned = df.dropna()
cleaned

,A,B
0,1.0,4.0


In [204]:
#18. df.fillna()
# Fills missing values with a specified value.
df = pd.DataFrame({'A': [1, None, 3]})
filled = df.fillna(0)
filled

,A
0,1.0
1,0.0
2,3.0


In [205]:
#19. df.isnull()
# Detects missing values.
df = pd.DataFrame({'A': [1, None, 3]})
nulls = df.isnull()
nulls

,A
0,False
1,True
2,False


In [206]:
#20. df.notnull()
# Detects non-missing values.
df = pd.DataFrame({'A': [1, None, 3]})
not_nulls = df.notnull()
not_nulls

,A
0,True
1,False
2,True


In [207]:
#21. df.sort_values()
# Sorts DataFrame by column values.
df = pd.DataFrame({'A': [3, 1, 2], 'B': [6, 4, 5]})
sorted_df = df.sort_values('A')
sorted_df

,A,B
1,1,4
2,2,5
0,3,6


In [208]:
#22. df.sort_index()
# Sorts DataFrame by index labels.
df = pd.DataFrame({'A': [1, 2, 3]}, index=[2, 0, 1])
sorted_df = df.sort_index()
sorted_df

,A
0,2
1,3
2,1


In [209]:
#23. df.reset_index()
# Resets the index of the DataFrame.
df = pd.DataFrame({'A': [1, 2, 3]}, index=['x', 'y', 'z'])
reset_df = df.reset_index()
reset_df

,index,A
0,x,1
1,y,2
2,z,3


In [210]:
#24. df.set_index()
# Sets a column as the DataFrame index.
df = pd.DataFrame({'A': ['x', 'y', 'z'], 'B': [1, 2, 3]})
indexed_df = df.set_index('A')
indexed_df

,B
A,
x,1
y,2
z,3


In [211]:
#25. df.pivot_table()
# Creates a spreadsheet-style pivot table.
df = pd.DataFrame({'Category': ['A', 'B', 'A'], 'Value': [1, 2, 3]})
pivot = df.pivot_table(values='Value', index='Category', aggfunc='sum')
pivot

,Value
Category,
A,4
B,2


In [212]:
#26. df.pivot()
# Reshapes data based on column values.
df = pd.DataFrame({'A': ['x', 'y'], 'B': ['a', 'b'], 'C': [1, 2]})
pivoted = df.pivot(index='A', columns='B', values='C')
pivoted

B,a,b
A,,
x,1.0,NaN
y,NaN,2.0


In [213]:
#27. df.melt()
# Unpivots a DataFrame from wide to long format.
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4], 'C': [5, 6]})
melted = df.melt(id_vars=['A'], value_vars=['B', 'C'])
melted

,A,variable,value
0,1,B,3
1,2,B,4
2,1,C,5
3,2,C,6


In [214]:
#28. df.apply()
# Applies a function along an axis of the DataFrame.
df = pd.DataFrame({'A': [1, 2, 3]})
ans = df.apply(lambda x: x * 2)
ans

,A
0,2
1,4
2,6


In [215]:
#29. df.applymap()
# Applies a function element-wise.
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
ans = df.applymap(lambda x: x ** 2)
ans

/tmp/ipython-input-765934954.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  ans = df.applymap(lambda x: x ** 2)


,A,B
0,1,9
1,4,16


In [217]:
# 30. df.map()
# Maps values of a Series using a dictionary or function.
s = pd.Series([1, 2, 3])
mapped = s.map({1: 'a', 2: 'b', 3: 'c'})
mapped

,0
0,a
1,b
2,c


In [221]:
#31. df.value_counts()
# Returns counts of unique values.
df = pd.DataFrame({'A': ['x', 'y', 'x', 'z', 'y', 'x']})
counts = df['A'].value_counts()
counts

,count
A,
x,3
y,2
z,1


In [222]:
#32. df.unique()
# Returns unique values from a Series.
s = pd.Series([1, 2, 2, 3, 3, 3])
unique_vals = s.unique()
unique_vals

array([1, 2, 3])

In [223]:
#33. df.nunique()
# Returns the number of unique values.
df = pd.DataFrame({'A': [1, 2, 2, 3, 3, 3]})
count = df['A'].nunique()
count

3

In [224]:
#34. df.rename()
# Renames columns or index labels.
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
renamed = df.rename(columns={'A': 'Column1', 'B': 'Column2'})
renamed

,Column1,Column2
0,1,3
1,2,4


In [225]:
#35. df.drop()
# Drops specified labels from rows or columns.
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
dropped = df.drop('B', axis=1)
dropped

,A
0,1
1,2
2,3


In [226]:
#36. df.drop_duplicates()
# Removes duplicate rows.
df = pd.DataFrame({'A': [1, 1, 2, 3], 'B': [4, 4, 5, 6]})
unique_df = df.drop_duplicates()
unique_df

,A,B
0,1,4
2,2,5
3,3,6


In [228]:
#37. df.duplicated()
# Returns boolean Series indicating duplicate rows.
df = pd.DataFrame({'A': [1, 1, 2]})
dups = df.duplicated()
dups

,0
0,False
1,True
2,False


In [230]:
#38. df.iloc[]
# Selects data by integer position.
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
row = df.iloc[0]
row

,0
A,1
B,4


In [232]:
#39. df.loc[]
# Selects data by label.
df = pd.DataFrame({'A': [1, 2, 3]}, index=['x', 'y', 'z'])
row = df.loc['x']
row

,x
A,1


In [235]:
#40. df.to_csv()
# Writes DataFrame to a CSV file.
# Create DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

# Save to Colab Downloads directory with a proper name
file_path = "/content/sample_dataframe_export.csv"

df.to_csv(file_path, index=False)

file_path


'/content/sample_dataframe_export.csv'